### PR TITLE
fix(hooks): install every hook module, not a hardcoded list

### PR DESCRIPTION
**Pull request by goashem**
Every install on 2.0.x ships a broken `post-write.js`.

## The bug

`init` and `update` copy hook scripts from a hardcoded array of filenames. `symbol-extractor.js` was added to `src/hooks/` but never to those arrays, so `.wolf/hooks/` gets a `post-write.js` that cannot resolve its own import:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module .../.wolf/hooks/symbol-extractor.js
imported from .../.wolf/hooks/post-write.js
```

The hook dies on every Write/Edit, so anatomy silently stops updating.

**It is invisible from inside a session.** The harness swallows hook stderr, and `openwolf status` checked only 7 entrypoint filenames — a list that had itself fallen behind (no `precompact.js`, `anatomy-store.js`, `anatomy-lock.js`) — so it happily reported `✓ All 7 hook scripts present` for a completely broken install. I only found it because anatomy stopped growing after upgrading a project from 1.0.4.

## Reproducing on 2.0.1

```bash
mkdir demo && cd demo && npm init -y && openwolf init --agent claude
ls .wolf/hooks/symbol-extractor.js      # No such file
echo "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"$PWD/index.js\"},\"cwd\":\"$PWD\"}" \
  | CLAUDE_PROJECT_DIR=$PWD node .wolf/hooks/post-write.js    # ERR_MODULE_NOT_FOUND
openwolf status                          # "✓ All 7 hook scripts present"
```

## The fix

Both copy sites now read the shipped hooks directory instead of naming files, so a module added later is installed automatically — the same class of bug cannot recur. `status` compares the install against what the package actually ships and names what is missing.

New `src/utils/hook-files.ts` holds the shared source-dir resolution, the entrypoint list (the files the harness invokes, still meaningful as a concept), and `listHookModules()`.

## After the fix

Same fresh `init` installs 11 modules, the hook exits 0, and:

```
✓ All 11 hook scripts present
```

Removing `symbol-extractor.js` by hand now gives:

```
✗ Missing 1 hook scripts: symbol-extractor.js
    Run: openwolf update
```

## Tests

`tests/hook-files.test.ts` installs what `listHookModules()` reports and walks each entrypoint's imports transitively. Restoring the hardcoded list fails it with `post-write.js has imports missing from the install: symbol-extractor.js`. Full suite: 31/31 passing, `tsc --noEmit` clean.

Note that `openwolf update` does not repair existing installs on its own until this ships — affected projects need the file copied in manually, or a re-`init`.

### CODE REVIEW

**Comment by cytostack** [comment]
Thanks @goashem. Your complete-hook installation approach was adapted in the [2.5.2 branch](https://github.com/cytostack/openwolf/tree/release/openwolf-2.5.2) and verified through package upgrade tests.
